name: jupyterlab-binder
channels:
  - conda-forge
dependencies:
  # Runtimes
  - python=3.14
  - nodejs=24
  - ruby=3.4
  # Package managers
  - pip
  # Core modules
  - jupyterlab=4.5.0
  - notebook=7.5.0
  # Kernels
  - ipykernel
  - xeus-python
  - xeus-cpp
  - xeus-lua
  # Languages
  - jupyterlab-language-pack-ru-RU
  # Extensions
  - jupyter-offlinenotebook
  # Python libraries
  - ipywidgets
  - ipyevents
  - ipympl
  - ipycanvas
  - ipyleaflet
  - nbconvert
  - plotly
  - bqplot
  # Additional packages
  - util-linux
  - git
  - cmake
  - vim
  - nano
  - micro
  - tree
  - bat
  - mc
  - ranger-fm
  - htop
  - screenfetch
